name = "shipchamber-relay"
main = "src/index.js"
compatibility_date = "2025-06-01"
account_id = "ed43fb9aedda947029c20ca03959f8da"
workers_dev = true

[[durable_objects.bindings]]
name = "RELAY_ROOM"
class_name = "RelayRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayRoom"]
